configured_endpoints: 43
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/privy%2Fprivy-api-client-eadf0de2c17aa9736e9d8e2448a01204765f0147acf2aaa8b3edb65b97d2f4af.yml
openapi_spec_hash: f4e7f9ba179f1281ecceec568535de45
config_hash: 1ccde73e77b74b5cdd4f6149df9c20ef
